/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { EmailService } from "../email.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { EmailCreateInput } from "./EmailCreateInput";
import { Email } from "./Email";
import { EmailFindManyArgs } from "./EmailFindManyArgs";
import { EmailWhereUniqueInput } from "./EmailWhereUniqueInput";
import { EmailUpdateInput } from "./EmailUpdateInput";
import { AttachmentFindManyArgs } from "../../attachment/base/AttachmentFindManyArgs";
import { Attachment } from "../../attachment/base/Attachment";
import { AttachmentWhereUniqueInput } from "../../attachment/base/AttachmentWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class EmailControllerBase {
  constructor(
    protected readonly service: EmailService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Email })
  @nestAccessControl.UseRoles({
    resource: "Email",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createEmail(@common.Body() data: EmailCreateInput): Promise<Email> {
    return await this.service.createEmail({
      data: data,
      select: {
        body: true,
        createdAt: true,
        id: true,
        receivedAt: true,
        recipient: true,
        sender: true,
        subject: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Email] })
  @ApiNestedQuery(EmailFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Email",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async emails(@common.Req() request: Request): Promise<Email[]> {
    const args = plainToClass(EmailFindManyArgs, request.query);
    return this.service.emails({
      ...args,
      select: {
        body: true,
        createdAt: true,
        id: true,
        receivedAt: true,
        recipient: true,
        sender: true,
        subject: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Email })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Email",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async email(
    @common.Param() params: EmailWhereUniqueInput
  ): Promise<Email | null> {
    const result = await this.service.email({
      where: params,
      select: {
        body: true,
        createdAt: true,
        id: true,
        receivedAt: true,
        recipient: true,
        sender: true,
        subject: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Email })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Email",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateEmail(
    @common.Param() params: EmailWhereUniqueInput,
    @common.Body() data: EmailUpdateInput
  ): Promise<Email | null> {
    try {
      return await this.service.updateEmail({
        where: params,
        data: data,
        select: {
          body: true,
          createdAt: true,
          id: true,
          receivedAt: true,
          recipient: true,
          sender: true,
          subject: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Email })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Email",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteEmail(
    @common.Param() params: EmailWhereUniqueInput
  ): Promise<Email | null> {
    try {
      return await this.service.deleteEmail({
        where: params,
        select: {
          body: true,
          createdAt: true,
          id: true,
          receivedAt: true,
          recipient: true,
          sender: true,
          subject: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/attachments")
  @ApiNestedQuery(AttachmentFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Attachment",
    action: "read",
    possession: "any",
  })
  async findAttachments(
    @common.Req() request: Request,
    @common.Param() params: EmailWhereUniqueInput
  ): Promise<Attachment[]> {
    const query = plainToClass(AttachmentFindManyArgs, request.query);
    const results = await this.service.findAttachments(params.id, {
      ...query,
      select: {
        createdAt: true,

        email: {
          select: {
            id: true,
          },
        },

        fileContent: true,
        fileSize: true,
        fileType: true,
        filename: true,
        id: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/attachments")
  @nestAccessControl.UseRoles({
    resource: "Email",
    action: "update",
    possession: "any",
  })
  async connectAttachments(
    @common.Param() params: EmailWhereUniqueInput,
    @common.Body() body: AttachmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      attachments: {
        connect: body,
      },
    };
    await this.service.updateEmail({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/attachments")
  @nestAccessControl.UseRoles({
    resource: "Email",
    action: "update",
    possession: "any",
  })
  async updateAttachments(
    @common.Param() params: EmailWhereUniqueInput,
    @common.Body() body: AttachmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      attachments: {
        set: body,
      },
    };
    await this.service.updateEmail({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/attachments")
  @nestAccessControl.UseRoles({
    resource: "Email",
    action: "update",
    possession: "any",
  })
  async disconnectAttachments(
    @common.Param() params: EmailWhereUniqueInput,
    @common.Body() body: AttachmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      attachments: {
        disconnect: body,
      },
    };
    await this.service.updateEmail({
      where: params,
      data,
      select: { id: true },
    });
  }
}
